#!/usr/bin/env bash
# Transfers a file from our client to a server
# Options:  [-i identity_file] [-o ssh_option] [[user@]host1:]file1
FILE_TRANS=$1
IP_SERVER=$2
USERNAME=$3
PATH_SSH=$4 # ~/.ssh/School
# [[$#]] Expands to the number of positional parameters in decimal
if [[ $# -lt 3 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$PATH_SSH" -o StrictHostKeyChecking=no "$FILE_TRANS" "$USERNAME@$IP_SERVER":~/
fi