#!/usr/bin/env bash
# Configure Nginx server so that redirecting other page
# Step 1: Install nginx: Update apt packaging system
sudo apt-get -y update
sudo apt-get -y install nginx
# Step 2: Adjust the firewall to allow access to the service,
# allow traffic on port 80
sudo ufw allow 'Nginx HTTP'
# Step 3: Adjust the document root /var/www/html
# Add the permissions (chmod in mode recursive): “rwxr-xr-x”
sudo chmod -R 755 /var/www/html/
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
# Step 4: Implement permanent redirect,
# use the built-in rewrite directive. Syntax: rewrite regex URL [flag]
#to_add = "\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=oofSnsGkops&list=RDoofSnsGkops&start_radio=1 permanent;"
sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=oofSnsGkops&list=RDoofSnsGkops&start_radio=1 permanent;" /etc/nginx/sites-available/default
# Step 5: Reload/restart Nginx with nginx command:
# To force close and restart Nginx and related processes
sudo /etc/init.d/nginx restart