#!/usr/bin/env bash
# Installs nginx, sets it up to listen on port 80 and creates a landing page
# Adds a custom 301 redireection page and custom 404 message
# Adds header = to X-Served-By $HOSTNAME
# shellcheck disable=SC2154

#updates apt repo
sudo apt-get update -y
sudo apt-get upgrade -y

# Installs nginx
sudo apt-get install nginx -y

#unlinks the default file
unlink /etc/nginx/sites-enabled/default

#creates the config file
echo "server {
	listen 80 default_server;
	index index.html;
	server_name hder.tech;
	root /var/www/html;
    add_header X-Served-By $HOSTNAME;
	location /redirect_me {
      return 301 https://www.youtube.com/watch?v=LFfVDyW6ddg\$request_uri;
      }
	error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html;
                internal;
        }
	}
" > /etc/nginx/conf.d/hder.tech.conf

#creates the index file
echo "Hello World" > /var/www/html/index.html;

#creates the index file
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html;

#restarts the server
sudo service nginx restart
