#!/usr/bin/env bash
# Activate again the web server running and listening on port 80 []
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# reload the Nginx processes
pkill -HUP nginx
