#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely, and 'I am invincible!!!' when receiving a SIGTERM.

_no_kill() {
	echo "I am invincible!!!"
}
trap _no_kill SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done