#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

c=0
while [ $c -lt 11 ]
do
    if [ $c = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    c=$((c+1))
done
