#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

c=0
while [ $c -lt 10 ]
do
    if [ $c = 3 ]
    then
        echo "bad luck"
    elif [ $c = 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    c=$((c+1))
done
